config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root to: "products#index"
  resources :products
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
require 'carrierwave/orm/activerecord'

class Product < ApplicationRecord
  mount_uploaders :images, ImageUploader

  validates :name, length: { maximum: 60 }, presence: true
  validates :images, presence: true
  validates :category_id, presence: true
  validates :link, length: { maximum: 100 }
  
  validates_length_of :images, :maximum => 6
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, :except => [:index]

  def index
    if params[:category_id]
      category_id = params[:category_id]
      @products = Product.where(category_id: category_id).order :name
    else
      @products = Product.order :name
    end
    @products = @products.page(params[:page]).per(2)
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
      flash[:notice] = "Novo Produto criado"
    else
      render :new
    end
  end

  def new
    @product = Product.new
    render "new"
  end

  def edit
    @product = Product.find(params[:id])
    render "edit"
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
      flash[:notice] = "Produto alterado"
    else
      render "edit"
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.remove_images!
    @product.save

    if @product.destroy
      redirect_to products_path
      flash[:notice] = "Produto excluído"
    else
      redirect_to products_path
      flash[:notice] = "Erro na exclusão"
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :link, :category_id,  {images: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductGallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to('Product Gallery', '/', class: 'navbar-brand') %>
        </div>
        <div class="collapse navbar-collapse pull-left">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Todas as categorias', products_path %>
            </li>
            <% Category.all.each do |category| %>
            <li>
              <%= link_to category.name, products_path(category_id: category.id) %>
            </li>
            <% end %>
          </ul>
        </div>
        <div class="collapse navbar-collapse pull-right">
          <ul class="nav navbar-nav">
            <% if admin_signed_in? %>
              <li>
                <%= link_to('Novo Produto', new_product_path) %>
              </li>
              <li>
                <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
              </li>
            <% else %>
              <li>
                <%= link_to 'Login', new_admin_session_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>

      <div class="row footer">
        <div class="col-lg-12">
          <p>2016 - 2º PL - Teste de Software - Product Gallery</p>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="page-header">
      Editar <small>Produto</small>
    </h1>
  </div>
</div>

<% if @product.errors.full_messages.any? %>
  <div class="alert alert-danger alert-dismissable">
    <% @product.errors.full_messages.each do |msg| %>
      <p>
        <i class="fa fa-warning"></i>  <%= msg %>
      </p>
    <% end %>
  </div>
<% end %>

<%= form_for @product, url: {action: "update"} do |f| %>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error has-feedback' if @product.errors[:name].present? %>">
        <label>Nome*</label>
        <%= f.text_field :name, class: "form-control" %>
        <% if @product.errors[:name].present? %>
          <span class="form-control-feedback">
            <i class="fa fa-warning"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error' if @product.errors[:category_id].present? %>">
        <label>Categoria*</label>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => "Selecione uma Categoria"}, {class: "form-control"}) %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error has-feedback' if @product.errors[:description].present? %>">
        <label>Descrição</label>
        <%= f.text_area :description, class: "form-control" %>
        <% if @product.errors[:description].present? %>
          <span class="form-control-feedback">
            <i class="fa fa-warning"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error has-feedback' if @product.errors[:link].present? %>">
        <label>Link para Venda</label>
        <%= f.text_field :link, class: "form-control" %>
        <% if @product.errors[:link].present? %>
          <span class="form-control-feedback">
            <i class="fa fa-warning"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-6">
      <div class="form-group <%= 'has-error' if @product.errors[:product_images].present? %>">
        <label>Imagens*</label>
        <%= f.file_field :images, multiple: true, accept: 'image/png,image/gif,image/jpeg', class: 'custom-file-input' %>
      </div>
    </div>
    <div class="col-xs-6 text-right m-t-20">
      <div class="form-group">
        <%= f.submit "Alterar", class: "btn btn-success" %>
        <%= link_to "Cancelar", root_url, class: "btn btn-link" %>
      </div>
    </div>
  </div>

<% end %>

app/views/products/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissable">
    <p><i class="fa fa-check"></i> <%= flash[:notice] %></p>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissable">
    <p><i class="fa fa-warning"></i> <%= flash[:error] %></p>
  </div>
<% end %>

<% if @products.length > 0 %>
  <% @products.each do |product| %>
    <div class="row">
      <div class="col-xs-6 m-t-20">
        <div class="row text-center">
          <div class="col-xs-12 lightgallery">
            <% product.images.each_with_index do |img, idx| %>
              <% if idx == 0 %>
                <a href="<%= img %>">
                  <div class="thumb-big" style="background-image: url('<%= img %>')"></div>
                </a>
              <% else %>
                <a href="<%= img %>" class="pull-left m-5">
                  <div class="thumb-small" style="background-image: url('<%= img %>')"></div>
                </a>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="row">
          <div class="col-md-8">
            <h3><%= product.name %></h3>
          </div>
          <% if admin_signed_in? %>
            <div class="col-md-4 text-right">
              <%= link_to edit_product_path(product), class: 'btn btn-primary m-t-20 m-r-5' do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to product_path(product), method: :delete, data: {confirm: 'Tem certeza?'}, class: 'btn btn-danger m-t-20' do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </div>
          <% end %>
        </div>
        <p class="break-word">
          <%= product.description %>
        </p>
        <% if product.link.length > 0 %>
          <%= link_to product.link, target: '_blank', class: 'btn btn-success btn-lg' do %>
            Comprar <i class="fa fa-shopping-cart"></i>
          <% end %>
        <% end %>
      </div>
    </div>
    <% if @products.length > 1 %><hr> <% end %>
  <% end %>
<% else %>
  <div class="alert alert-warning alert-dismissable">
    <p class="text-center">
      Não há produtos para exibição
    </p>
  </div>
<% end %>

<div class="row text-center">
  <div class="col-lg-12">
    <%= paginate @products %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $(".lightgallery").lightGallery({
      thumbnail:true
    });
  });
</script>

app/views/products/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="page-header">
      Novo <small>Produto</small>
    </h1>
  </div>
</div>

<% if @product.errors.full_messages.any? %>
  <div class="alert alert-danger alert-dismissable">
    <% @product.errors.full_messages.each do |msg| %>
      <p>
        <i class="fa fa-warning"></i>  <%= msg %>
      </p>
    <% end %>
  </div>
<% end %>

<%= form_for @product, url: {action: "create"} do |f| %>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error has-feedback' if @product.errors[:name].present? %>">
        <label>Nome*</label>
        <%= f.text_field :name, class: "form-control" %>
        <% if @product.errors[:name].present? %>
          <span class="form-control-feedback">
            <i class="fa fa-warning"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error' if @product.errors[:category_id].present? %>">
        <label>Categoria*</label>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => "Selecione uma Categoria"}, {class: "form-control"}) %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error has-feedback' if @product.errors[:description].present? %>">
        <label>Descrição</label>
        <%= f.text_area :description, class: "form-control" %>
        <% if @product.errors[:description].present? %>
          <span class="form-control-feedback">
            <i class="fa fa-warning"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group <%= 'has-error has-feedback' if @product.errors[:link].present? %>">
        <label>Link para Venda</label>
        <%= f.text_field :link, class: "form-control" %>
        <% if @product.errors[:link].present? %>
          <span class="form-control-feedback">
            <i class="fa fa-warning"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-xs-6">
      <div class="form-group <%= 'has-error' if @product.errors[:product_images].present? %>">
        <label>Imagens*</label>
        <%= f.file_field :images, multiple: true, accept: 'image/png,image/gif,image/jpeg', class: 'custom-file-input' %>
      </div>
    </div>
    <div class="col-xs-6 text-right m-t-20">
      <div class="form-group">
        <%= f.submit "Criar", class: "btn btn-success" %>
        <%= link_to "Cancelar", root_url, class: "btn btn-link" %>
      </div>
    </div>
  </div>

<% end %>